[package]
name = "engine"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = { workspace = true }
ruci = { workspace = true, features = ["gui-sync"] }
shakmaty = { workspace = true }
