[package]
name = "ruci"
version = "0.3.2"
edition = "2021"
authors = ["Leonard D. <tigerros.gh@gmail.com>"]
description = "A UCI (Universal Chess Interface) crate."
license = "GPL-3.0"
repository = "https://github.com/tigerros/ruci"
categories = ["parser-implementations", "game-development"]
keywords = ["chess", "uci", "parser"]
include = ["src", "README.md"]

[package.metadata.docs.rs]
features = ["uci-connection"]

[[example]]
name = "go_async_info"
path = "examples/go_async_info.rs"
required-features = ["uci-connection"]

[[example]]
name = "go"
path = "examples/go.rs"
required-features = ["uci-connection"]

[dependencies]
shakmaty = "0.27.1"
paste = "1.0.15"
dry-mods = "0.1.5"
parking_lot = { version = "0.12.3", features = ["arc_lock", "send_guard"], optional = true }
tokio = { version = "1.39.2", features = ["rt", "sync", "io-std", "io-util", "process"], optional = true }

[dev-dependencies]
pretty_assertions = "1.4.0"
tokio = { version = "1.39.2", features = ["full"] }

[features]
default = []
uci-connection = ["tokio", "parking_lot"]