[package]
name = "ruci"
version = "0.5.5"
edition = "2021"
authors = ["Leonard D. <tigerros.gh@gmail.com>"]
description = "A UCI (Universal Chess Interface) crate."
license = "GPL-3.0"
repository = "https://github.com/tigerros/ruci"
categories = ["parser-implementations", "game-development"]
keywords = ["chess", "uci", "parser"]
include = ["src", "README.md"]
rust-version = "1.75.0"

[package.metadata.docs.rs]
features = ["engine-connection"]

[[example]]
name = "go_async_info"
path = "examples/go_async_info.rs"
required-features = ["engine-connection"]

[[example]]
name = "go"
path = "examples/go.rs"
required-features = ["engine-connection"]

[dependencies]
shakmaty = "~0.27"
paste = "1"
dry-mods = "~0.1"
parking_lot = { version = "~0.12", features = ["arc_lock", "send_guard"], optional = true }
tokio = { version = "1", default-features = false, features = ["rt", "sync", "io-util", "process", "parking_lot"], optional = true }
serde = { version = "1", default-features = false, features = ["derive"], optional = true }

[dev-dependencies]
pretty_assertions = "1"
tokio = { version = "1", default-features = false, features = ["macros", "rt-multi-thread", "time"] }
criterion = { version = "~0.5", features = ["html_reports"] }
shakmaty-uci = "~0.1"
vampirc-uci = "~0.11"

[[bench]]
name = "comparison"
harness = false

[features]
default = []
serde = ["serde/derive", "shakmaty/serde"]
engine-connection = ["tokio", "parking_lot"]
