[package]
name = "ruci"
version = "0.1.1"
edition = "2021"
authors = ["Leonard D. <tigerros.gh@gmail.com>"]
description = "A UCI (Universal Chess Interface) crate."
license = "GPL-3.0"
repository = "https://github.com/tigerros/ruci"
categories = ["parser-implementations", "game-development"]
keywords = ["chess", "uci", "parser"]
include = ["src", "README.md"]

[dependencies]
shakmaty = "0.27.0"
paste = "1.0.14"
dry-mods = "0.1.5"

[dev-dependencies]
assert_cmd = "2.0.14"