[package]
name = "ruci"
version = "0.8.1"
edition = "2021"
authors = ["Leonard D. <tigerros.gh@gmail.com>"]
description = "A UCI (Universal Chess Interface) crate."
license = "GPL-3.0"
repository = "https://github.com/tigerros/ruci"
categories = ["parser-implementations", "game-development"]
keywords = ["chess", "uci", "parser"]
include = ["src", "README.md"]
rust-version = "1.81.0"

[package.metadata.docs.rs]
features = ["engine-connection"]

[[example]]
name = "go_async_info"
path = "examples/go_async_info.rs"
required-features = ["engine-connection"]

[[example]]
name = "go"
path = "examples/go.rs"
required-features = ["engine-connection"]

[[example]]
name = "no_std"
path = "examples/no_std.rs"

[dependencies]
shakmaty = "~0.27"
paste = "1"
dry-mods = "~0.1"
tokio = { version = "1", default-features = false, features = ["io-util", "process"], optional = true }
serde = { version = "1", default-features = false, features = ["derive"], optional = true }

[dev-dependencies]
pretty_assertions = { version = "1", features = ["unstable"] }
tokio = { version = "1", default-features = false, features = ["rt-multi-thread", "macros", "sync", "time"] }
criterion = { version = "~0.5", features = ["html_reports"] }
shakmaty-uci = "~0.1"
vampirc-uci = "~0.11"
anyhow = "1"

[[bench]]
name = "comparison"
harness = false

[features]
default = []
serde = ["dep:serde", "shakmaty/serde"]
engine-connection = ["tokio"]
