[package]
name = "ruci"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "main"
path = "src/bin/main.rs"

[dependencies]
shakmaty = "0.27.0"
paste = "1.0.14"
dry-mods = "0.1.5"
log = "0.4.21"

[dev-dependencies]
assert_cmd = "2.0.14"