[package]
name = "ruci"
version = "0.1.0"
edition = "2021"
description = "A UCI (Universal Chess Interface) crate."
license = "GPL-3"

[dependencies]
shakmaty = "0.27.0"
paste = "1.0.14"
dry-mods = "0.1.5"

[dev-dependencies]
assert_cmd = "2.0.14"