[package]
name = "ruci"
version = "0.2.4"
edition = "2021"
authors = ["Leonard D. <tigerros.gh@gmail.com>"]
description = "A UCI (Universal Chess Interface) crate."
license = "GPL-3.0"
repository = "https://github.com/tigerros/ruci"
categories = ["parser-implementations", "game-development"]
keywords = ["chess", "uci", "parser"]
include = ["src", "README.md"]

[[example]]
name = "go_stop"
path = "examples/go_stop.rs"
required-features = ["uci-connection"]

[dependencies]
shakmaty = "0.27.0"
paste = "1.0.14"
dry-mods = "0.1.5"
tokio = { version = "1.37.0", features = ["io-std", "io-util", "process"], optional = true }
parking_lot = { version = "0.12.2", features = ["arc_lock"], optional = true }

[dev-dependencies]
pretty_assertions = "1.4.0"
tokio = { version = "1.37.0", features = ["io-std", "io-util", "process", "rt-multi-thread", "macros", "sync", "time"] }

[features]
default = []
uci-connection = ["tokio"]