[package]
name = "ruci"
version = "0.8.2-dev"
description = "A UCI (Universal Chess Interface) crate."
categories = ["parser-implementations", "game-development"]
keywords = ["chess", "uci", "parser"]
include = ["src", "README.md", "LICENSE"]
rust-version = "1.81.0"
edition = "2021"
authors = ["Leonard D. <tigerros.gh@gmail.com>"]
license = "GPL-3.0"
repository = "https://github.com/tigerros/ruci"

[dependencies]
shakmaty = { version = "~0.27", default-features = false }
paste = { version = "1", default-features = false }
dry-mods = { version = "~0.1", default-features = false }
maybe-async = { version = "~0.2", default-features = false }
tokio = { version = "1", optional = true, features = ["io-util", "process"] }
serde = { version = "1", optional = true, features = ["derive"] }

[features]
default = []
serde = ["dep:serde", "shakmaty/serde"]
std = ["shakmaty/std"]
tokio = ["shakmaty/std", "dep:tokio"]

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
maybe-async = { version = "~0.2" }
pretty_assertions = { version = "1", features = ["unstable"] }
criterion = { version = "~0.5", features = ["html_reports"] }
shakmaty-uci = "~0.1"
vampirc-uci = "~0.11"

[[bench]]
name = "comparison"
harness = false

[workspace]
members = ["examples/*"]

[workspace.dependencies]
ruci = { version = "0.8.2-dev", path = "." }