[[IgnoredVulns]]
id = "RUSTSEC-2024-0436"
reason = "Nothing suggests that there's something wrong with `paste` itself. Being unmaintaned is suspicious, but given the circumstances (simple macro - no runtime, wide usage, reputable author) I think it's fine. `pastey` is one \"successor\", but I haven't seen official endorsement, so I'm wary."