[package]
name = "go-tokio"
publish = false
version = "0.0.0"
edition = "2021"

[dependencies]
ruci = { workspace = true, features = ["engine-async"] }
tokio = { workspace = true, features = ["full"] }
anyhow = { workspace = true }