[package]
name = "go-tokio"
publish = false
version = "0.0.0"
edition = "2024"

[dependencies]
ruci = { workspace = true, features = ["tokio"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1"