[package]
name = "go-tokio"
publish = false
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
ruci = { workspace = true, features = ["engine-async", "tokio-process"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "process"] }
