[package]
name = "go-std"
publish = false
version = "0.0.0"
edition = "2024"

[dependencies]
ruci = { workspace = true, features = ["std"] }
shakmaty = { version = "~0.27", features = ["std"] }
anyhow = "1"