[package]
name = "go-std"
publish = false
version = "0.0.0"
edition = "2021"

[dependencies]
ruci = { workspace = true, features = ["engine-sync", "serde"] }
shakmaty = { workspace = true, features = ["std"] }
anyhow = { workspace = true }