[package]
name = "go-std"
publish = false
version = "0.0.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
ruci = { workspace = true, features = ["engine-sync"] }
shakmaty = { workspace = true, features = ["std"] }
