[package]
name = "go"
version = "0.1.0"
edition = "2024"

[dependencies]
ruci = { workspace = true, features = ["engine-connection-sync"] }
shakmaty = { workspace = true, features = ["std"] }
anyhow = "1"