[package]
name = "flexible-io"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow = { workspace = true }
ruci = { workspace = true, features = ["engine-async"] }
tokio = { workspace = true, features = ["full"] }
