name: Check
on: [push, pull_request]

jobs:
  check:
    strategy:
      matrix:
        toolchain:
          - "1.85.1" # remember to update rust-version in Cargo.toml
          - "stable"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: taiki-e/install-action@cargo-hack
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          targets: x86_64-unknown-none

      - name: Main
        run: rustup run ${{ matrix.toolchain }} cargo hack check --feature-powerset --lib --bins --examples
      - name: No-std
        run: rustup run ${{ matrix.toolchain }} cargo hack check --feature-powerset --skip io,engine-sync,engine-async,gui-sync,gui-async,tokio-process --target x86_64-unknown-none
  check-nightly:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: taiki-e/install-action@cargo-hack
      - uses: dtolnay/rust-toolchain@nightly

      - name: Main
        run: rustup run nightly cargo hack check --feature-powerset --workspace --all-targets -Z direct-minimal-versions