name: Check SemVer
on: [push, pull_request]

jobs:
  check-semver:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Check SemVer
        uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          feature-group: all-features