name: Deploy docs

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Doc
      run: cargo doc --no-deps
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: target/doc