name: Deploy docs

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Doc
      run: cargo doc --no-deps
    - name: Create index.html
      run: echo "<!DOCTYPE html><head><meta http-equiv='refresh' content='0; url=ruci/index.html'><script type='text/javascript'>window.location.href = 'ruci/index.html'</script></head><body><a href='ruci/index.html'>Doc link</a></body>" > target/doc/index.html
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: target/doc
        branch: docs