name: Lints
on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Check
        run: cargo check --workspace --examples --tests
  check-formatting:
    needs: [ check ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Format
        run: cargo fmt --all -- --check
  clippy:
    needs: [ check ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Clippy
        run: cargo clippy --workspace --examples --tests -- --warn clippy::pedantic --warn clippy::nursery --deny warnings